export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAIL = "POST_PRODUCT_FAIL"

export const GET_ONEPRODUCT_SUCCESS = "GET_ONEPRODUCT_SUCCESS"
export const GET_ONEPRODUCT_FAIL = "GET_ONEPRODUCT_FAIL"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const SEARCH_PRODUCT = "SEARCH_PRODUCT"
